# Generated by Django 2.1 on 2023-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('trade_date', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('pre_close', models.FloatField()),
                ('change', models.FloatField()),
                ('pct_chg', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ['trade_date'],
            },
        ),
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
